In [3]:
############################
# Import Required Libraries

import pandas as pd
import numpy as np

In [ ]:
import time
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from pandas import DataFrame
from sklearn.preprocessing import StandardScaler

In [34]:
#########################
# Read the cleaned data
def productLabels(s):
    s = s.strip().lower()
    if s == "womenclothing":
        return 1
    if s == "menclothing":
        return 2
    if s == "otherclothing":
        return 3
    return 0
#traindf = pd.read_csv('Train_Kaggle.csv',parse_dates=[['Year','Month']],converters={"ProductCategory":productLabels})
traindf = pd.read_csv('Train_Kaggle.csv',converters={"ProductCategory":productLabels})
traindf['ProductCategory'].unique()
traindf = traindf.fillna(method='bfill')


testdf = pd.read_csv('Test_Kaggle.csv',converters={"ProductCategory":productLabels})
testdf['ProductCategory'].unique()
test_for_kaggle = testdf.iloc[:,:-1]

In [25]:
from sklearn.model_selection import train_test_split
X=traindf.iloc[:,:-1]
y=traindf.iloc[:,3:4]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [27]:
y_test

     Sales(In ThousandDollars)
201                     4067.0
213                     5664.0
138                     3558.0
177                     4865.0
15                      2220.0
111                     2800.0
182                     1172.0
73                       487.0
205                     1056.0
139                      731.0
159                     3360.0
30                      2521.0
190                      785.0
9                       2662.0
67                       669.0
176                     1209.0
172                      785.0
18                      2164.0
154                      718.0
66                      3276.0
186                     4268.0
142                     1080.0
79                       599.0
25                       579.0
104                     1147.0
146                     1036.0
161                     1261.0
16                       607.0
45                       630.0
199                      655.0
..                         ...
117                     3724.0
93                      3245.0
84                      3340.0
95                      1001.0
137                     1158.0
211                      803.0
86                      1027.0
163                      648.0
153                     3883.0
38                       945.0
24                      2421.0
170                     1043.0
120                     3800.0
29                       914.0
19                       575.0
69                      4360.0
97                       643.0
60                      2919.0
68                      1035.0
5                        859.0
136                      710.0
56                       937.0
100                      682.0
152                     1346.0
82                       690.0
65                       930.0
109                      525.0
183                     3381.0
31                       620.0
12                      2732.0

[72 rows x 1 columns]

In [38]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# Create linear regression object
regr = linear_model.LinearRegression()
# Train the model using the training sets
regr.fit(X_train, y_train)
# Make predictions using the testing set
y_pred = regr.predict(X_test)

# The coefficients
print('Coefficients: \n', regr.coef_)
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))
# Explained variance score: 1 is perfect prediction
print('Variance score: %.2f' % r2_score(y_test, y_pred))

Coefficients:
 [[ 145.67587601   44.02405553 -843.92187014]]
Mean squared error: 878488.07
Variance score: 0.51

NameError: name 'accuracy' is not defined

In [37]:
kaggle_pred = regr.predict(test_for_kaggle)
kaggle_pred

array([[2871.75704572],
       [2027.83517558],
       [1183.91330544],
       [2915.78110125],
       [2071.85923111],
       [1227.93736097],
       [2959.80515679],
       [2115.88328665],
       [1271.96141651],
       [3003.82921232],
       [2159.90734218],
       [1315.98547204],
       [3047.85326785],
       [2203.93139771],
       [1360.00952757],
       [3091.87732339],
       [2247.95545325],
       [1404.03358311],
       [3135.90137892],
       [2291.97950878],
       [1448.05763864],
       [3179.92543446],
       [2336.00356432],
       [1492.08169418],
       [3223.94948999],
       [2380.02761985],
       [1536.10574971],
       [3267.97354552],
       [2424.05167538],
       [1580.12980524],
       [3311.99760106],
       [2468.07573092],
       [1624.15386078],
       [3356.02165659],
       [2512.09978645],
       [1668.17791631]])